#!/bin/bash

echo "Running custom TmpestBot one-time environment setup"
cd /home/ubuntu
echo "Changing working directory to: $(pwd)"
echo "Installing 'jq' to process JSON"
sudo snap install jq
echo "Updating apt-get"
sudo apt-get update
echo "Installing the aws cli"
sudo apt-get install awscli -y
echo "Install ruby"
sudo apt-get install gcc -y
sudo apt install gnupg2
gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm get head
rvm install
echo "Install gems"
gem install discordrb
gem install pry-debug
echo "Setting environment variables"
export TMPEST_BOT_DISCORD_TOKEN=$(aws ssm get-parameter --name 'tmpest-bot-discord-token-id' --region 'us-west-2' | jq -r .Parameter.Value)
echo "done"
